### PR TITLE
Nosplash does not work

### LINKED ISSUE #137: Argument -nosplash doesn't work
At least on my machine...
I provided a pull request which fixed the problem for me.

### PR DESCRIPTION
**Pull request by ThomasChr**
fixes #137

### CODE REVIEW

**Comment by ThomasChr** [comment]
PS: I have no idea where those two commits are coming, but the changes seem to be correct, so no worries there, I assume.

**Comment by lolo101** [comment]
Could you also add a test to show how the current code does not fit your need and how the change fixes it?

**Comment by ThomasChr** [comment]
The old code didn‘t work at all for me.
As I remember (not at a computer atm) the Filter for the argument returned "-nosplash" and the test for "isYesValue" did not recognize that as a yes value and showed the splash screen anyway.
Can you reproduce the same error or should I try to explain more tomorrow?

**Comment by ThomasChr** [comment]
So, back on a computer and ready to do some digging!
I'm on master, commit ecf02643e0526ae68ddd51226130603d005c0ec8 which is the most recent one.
First I'm running `mvn clean` and afterwards `mvn package` to make sure my msgviewer.jar matches the source code!

Now I'm running msgviewer.jar with the nosplash parameter:
image

And when I run it, what happens?
Here he is:
image
(I tricked a little bit to get this screenshot because when running msgviewer without a file the splashscreen is very fast!)

Now we're getting the debugger out!
I'm here: at.redeye.FrameWork.base.BaseModuleLauncher#splashEnabled

Let's dig into `StringUtils.isYes` and see what the paramters are there:
image

So we got the String "-nosplash" wich isn't considered a yes-value.
And yes, our debugger is stepping into showing the splash screen:
image

I'm not quite sure why such an obvious problem hasn't emerged earlier. Maybe it's some Java Magic I don't understand?
(I'm no Java Guy)

If I'm on the wrong track here (that could absolutely be!) can you figure out what I've done wrong?

**Comment by ThomasChr** [comment]
As I'm checking for a non empty string, woulndn't those other values still work? I think they are non-empty strings after all, aren't they?

Glad you're willing to help. I would also add some tests but I'm not quite sure how to test if the splash screen is showing up.

**Comment by lolo101** [comment]
You still need to make the difference between both non-empty strings "yes" and "no" :wink:

**Comment by ThomasChr** [comment]
Ohhh. It can be no.
Yep, that makes sense :-)

**Comment by lolo101** [comment]
Hi @ThomasChr 

I add a failing test to help fix the code in branch [nospash](https://github.com/lolo101/MsgViewer/tree/nospash)
Can you take a look?

**Comment by ThomasChr** [comment]
I‘m on vacation atm, but will take a look soon.
Thanks a lot so far!
Thomas

**Comment by ThomasChr** [comment]
What do you think about that? I merged your tests into my branch and fixed them. To me they are all green now:
image

**Comment by lolo101** [comment]
That's a smart solution :slightly_smiling_face: 

I'll merge it via the command line since GitHub detects a conflict. Thank you for the fix!

**Comment by ThomasChr** [comment]
You‘re very welcome!
Thanks a lot for the tests!

**Comment by lolo101** [comment]
The code has been merged to master! I close this merge-request

**Pull request closed without merging**
